### ISSUE TITLE
loop dot movements (SP 26)

### ISSUE THREAD

**Issue by SimonThormeyer** [SimonThormeyer/beuthSoundGroup#106]
As a User, I want to be able to loop the dragging of effect and sound parameter dots. 

**description of the story**

Detailed Description of the User-Story:
<to be added>

**acceptance criteria**
- [ ] the effect dot dragging that is done during recording of a looper is played back

**tickets or tasks**

**story points**
/estimate 13

** duplicate of #136 **

**Comment by MalteMittrowann** [comment]
Dieser Epic wird mit #136 , dem Duplikat, zusammengeführt und archiviert!
