### ISSUE TITLE
Frontend Struktur in Wiki

### ISSUE THREAD

**Issue by fr3ddykrueger** [SimonThormeyer/beuthSoundGroup#11]
Frontend Struktur wird verschriftlicht und/oder verbildlicht und in ein WIki eingefügt.

Termin-Planung in WIKI einbinden!

**Beschreibung:**

Wir wollen Docker-Container benutzen, damit wir unabhängig von Betriebssystemen programmieren können und nicht die zu verwendenden Packages manuell installieren müssen.

**Akzeptanzkriterien:**
- [x] Erstellung von einer Wiki-Homepage / Inhaltsverzeichnis
- [x] Modellierung & Verschriftlichung der Frontend-Struktur
- [x] geeignete Darstellung in der WIKI

**Beinhaltet Tickets:**
#2

**Comment by MalteMittrowann** [comment]
Die Tabellen sind jetzt sowohl für's Front- wie auch Back-End im WIKI erstellt
