### ISSUE TITLE
Ordnerstruktur erstellen

### ISSUE THREAD

**Issue by fr3ddykrueger** [SimonThormeyer/beuthSoundGroup#12]
Erstellung von Container-, Komponenten- und Modulstruktur.

#2

**Comment by SimonThormeyer** [comment]
frontend
├── node_modules
├── package.json
├── .gitignore
├── public
│   ├── favicon.ico
│   ├── index.html
│   ├── logo192.png
│   ├── logo512.png
│   ├── manifest.json
│   └── robots.txt
└── src
    ├── index.js
    ├── index.css
    ├── components
    |   ├── toneJS
    |   |   ├── synth.js
    |   |   └── ...
    |   ├── threeJS
    |   |   ├── canvas.js
    |   |   └── ...
    |   ├── ...
    |   └── ...
    ├── containers   
    |   └── App.js
    └── ...
