### ISSUE TITLE
Three.js Canvas erstellen

### ISSUE THREAD

**Issue by LucaPomer** [SimonThormeyer/beuthSoundGroup#14]
ein Canvas das klickbar ist auf dem Bildschirm.

**Beschreibung:**

**Akzeptanzkriterien:**

**Zugehoerige Storys:**
#1

**Comment by SimonThormeyer** [comment]
Das Canvas ist eine React-Komponente.
Vorschlag: das 'isomorphe Modell' wird an diese Komponente übergeben. Beim Klick wird eine Funktion auf dem Modul aufgerufen, übergeben
