### ISSUE TITLE
Function to move dots (User Story #156)

### ISSUE THREAD

**Issue by MalteMittrowann** [SimonThormeyer/beuthSoundGroup#166]
**Description of the Ticket:**

The random notes function will be expanded with the function to move the three dots in random directions.

**Is part of story** #156 

ToDo's:
- [x] Create a function that moves a dot according to coordinates
- [x] Move dots randomly on the canvas
- [x] make sure the dots stay on the canvas
- [x] call and toggle the function with the "Random Notes"-Button

**Comment by SimonThormeyer** [comment]
If we want to implement it similarly to the other part of the Looper (which I think is best) the function will be part of Canvas.js and given to the lopper, just like CanvasClick.
