### ISSUE TITLE
Frontend-Struktur

### ISSUE THREAD

**Issue by SimonThormeyer** [SimonThormeyer/beuthSoundGroup#2]
Als EntwicklerIn möchte ich im Frontend eine klare, komponentenbasierte Struktur haben, damit ich beim Programmieren den Überblick behalten kann.

**description of the story**

Zu Beginn der Programmierung müssen wir die Vorraussetzungen, Ordnerstrukturen und erforderlichen Tools anlegen und vorbereiten.

**blocked by**

**acceptance criteria**

**tickets or tasks**
- [x] Auf die zu verwendeten Tools einigen
Tools: three.js, tone.js, react, Yarn
- [x] Ein systematisches Dokument mit der Architektur der Tools anlegen ( #11  )
- [x] Frontend-Projekt anlegen (`yarn create-react-app`?)
- [x] Ordnerstruktur anlegen (#12 )
- [x] Globale Zustandsverwaltung anlegen (#58)

**story points**
/estimate 13

**Comment by SimonThormeyer** [comment]
@MalteMittrowann sollen wir den Punkt einfach abhaken mit dem systematischen Dokument? Der Bedarf dafür ist glaub ich nicht da, außer die Projektstruktur wird nochmal komplexer.

**Comment by MalteMittrowann** [comment]
Ich habe die Tabellen im WIKI als Dokumentation jetzt erstellt!

Damit ist diese UserStory meiner Meinung nach Erfüllt :-)
