### ISSUE TITLE
volume mixer: volume is too low too fast

### ISSUE THREAD

**Issue by SimonThormeyer** [SimonThormeyer/beuthSoundGroup#206]
this is due to the fact that volume is implemented as a logarithmic scale in ToneJS. 
So the value has to be set with respect to that fact.
Something like this:
`// expects value between 0 and 1`
`this.controllableVolume.volume.value = 10^(value * <range>) - <normalizingValue>;`

on value 0 the volume should be muted:
`this.controllableVolume.mute = (value === 0);`

**Comment by NiklasKramer** [comment]
Fixe das. Die fader waren noch nicht als ich die Funktion geschrieben habe.
