### ISSUE TITLE
Write own Synth Engine with ToneJS

### ISSUE THREAD

**Issue by NiklasKramer** [SimonThormeyer/beuthSoundGroup#73]
As a Developer, I want create my own synth engine to tailor the sound to my specific needs

**description of the story**

To enable a bigger variety in sound and unique sound profile to our product we would like to implement our own synth engine, based on Harmonic Synthesis.

**acceptance criteria**
- [x] ADSR
- [x] Accepts notes like "D6"
- [x] parameters are editable

**tickets or tasks**
- [x] implementation

**Comment by MalteMittrowann** [comment]
Done
