### ISSUE TITLE
Dot Parameter communicate with ToneJS

### ISSUE THREAD

**Issue by NiklasKramer** [SimonThormeyer/beuthSoundGroup#78]
As a user, I want the Dots to control Sound(Synth) / Effects, so that I can have more control of  the sounds of my creations.

**Description:**

On the canvas three buttons are created that send there relative position to the logic.
These parameters control the effects and sounds of the tone.js-synthesizers. Each one effects one parameter:
- the effects on the synthesizer
- the effect on the room

**blocked by**
- [x] Dots send their position data and are visualized (#69  )

**acceptance criteria**
- [x] Three points are shown on the canvas
- [x] every points sends its realitve coordinates to MusicCTRL
- [x] there are complex changes

**tickets or tasks**
- [x] connect Dots to basic effect parameters
- [x] connect Dots to basic synth parameters
- [x] dots lead to complex changes #78 

**story points**
/estimate 13

**Comment by MalteMittrowann** [comment]
Diese User-Story erkläre ich mal für abgeschlossen
