### ISSUE TITLE
Dots movement lead to complex Parameter Changes (User Story #78)

### ISSUE THREAD

**Issue by NiklasKramer** [SimonThormeyer/beuthSoundGroup#92]
Description of the Ticket:
Create advanced parameter parameter movements for multiple Synth & Effect Parameters

**Is part of story** #78

ToDo's:
- [ ] complex synth parameter movements
- [ ] complex effect parameter options

**Comment by MalteMittrowann** [comment]
Dieses Ticket wird geschlossen und die weitere Anpassung der Parameter-Werte erfolgt in anderen Tickets
